apiVersion: v1
kind: Secret
metadata:
  name: gta-backend-secrets
type: Opaque
stringData:
  # Secrets will be injected by GitHub Actions using envsubst
  SECRET_KEY: "${SECRET_KEY}"
  GEMINI_API_KEY: "${GEMINI_API_KEY}"
  MONGO_URI: "${MONGO_URI}"
  MONGODB_DB_NAME: "${MONGODB_DB_NAME}"
